"""New Migration1

Revision ID: 120a568ac10c
Revises: 754f9c0e3a7c
Create Date: 2022-01-19 09:40:18.917046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120a568ac10c'
down_revision = '754f9c0e3a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
